import comp from "D:/node/Yaoweb5/.vscode/.vp-temp/pages/tools/git/git_client.html.vue"
const data = JSON.parse("{\"path\":\"/tools/git/git_client.html\",\"title\":\"4.图像化客户端推荐\",\"lang\":\"zh-CN\",\"frontmatter\":{\"category\":[\"工具\"],\"tag\":[\"工具\",\"技巧\",\"教程\",\"git\"],\"order\":4,\"permalink\":\"/tools/git/git_client.html\",\"description\":\"4.图像化客户端推荐 有一些工作流比较复杂，同时涉及到多条命令，除非是自动化工作流，否则使用命令不仅难以记忆，操作效率也会很慢。 而且 文件会改动对比 这种事情用 图形化展示也会比较好一点。 GitHub Desktop 由 GitHub 开发的完全免费且开源的可自定义的 GUI 客户端程序。提供 Windows 和 macOS 版本。界面非常简洁，功...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://yaoabcde.github.io/Yao/Yao/tools/git/git_client.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"YAO\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"4.图像化客户端推荐\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"4.图像化客户端推荐 有一些工作流比较复杂，同时涉及到多条命令，除非是自动化工作流，否则使用命令不仅难以记忆，操作效率也会很慢。 而且 文件会改动对比 这种事情用 图形化展示也会比较好一点。 GitHub Desktop 由 GitHub 开发的完全免费且开源的可自定义的 GUI 客户端程序。提供 Windows 和 macOS 版本。界面非常简洁，功...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2024-10-07T16:48:13.000Z\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"工具\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"技巧\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"教程\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"git\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2024-10-07T16:48:13.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"4.图像化客户端推荐\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":\\\"2024-10-07T16:48:13.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Yao\\\",\\\"url\\\":\\\"https://baidu.com\\\",\\\"email\\\":\\\"1964877312@qq.com\\\"}]}\"]]},\"headers\":[{\"level\":3,\"title\":\"GitHub Desktop\",\"slug\":\"github-desktop\",\"link\":\"#github-desktop\",\"children\":[]},{\"level\":3,\"title\":\"Sourcetree\",\"slug\":\"sourcetree\",\"link\":\"#sourcetree\",\"children\":[]},{\"level\":2,\"title\":\"GitKraken\",\"slug\":\"gitkraken\",\"link\":\"#gitkraken\",\"children\":[]}],\"git\":{\"createdTime\":1728311364000,\"updatedTime\":1728319693000,\"contributors\":[{\"name\":\"YAO\",\"email\":\"1964877312@qq.com\",\"commits\":3}]},\"readingTime\":{\"minutes\":0.94,\"words\":282},\"filePathRelative\":\"tools/git/4.图像化客户端推荐.md\",\"localizedDate\":\"2024年10月7日\",\"excerpt\":\"\\n<p>有一些工作流比较复杂，同时涉及到多条命令，除非是自动化工作流，否则使用命令不仅难以记忆，操作效率也会很慢。<br>\\n而且 文件会改动对比 这种事情用 图形化展示也会比较好一点。</p>\\n<h3>GitHub Desktop</h3>\\n<p>由 GitHub 开发的完全免费且开源的可自定义的 GUI 客户端程序。提供 Windows 和 macOS 版本。界面非常简洁，功能也非常实用。</p>\\n<p>官网地址：<br>\\n<a href=\\\"https://github.com/apps/desktop\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">https://github.com/apps/desktop</a></p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
