export const redirects = JSON.parse("{\"/Yao/myblog/%E5%85%B3%E4%BA%8E%E6%9C%AC%E7%AB%99.html\":\"/Yao/myblog/web.html\",\"/Yao/myblog/%E6%A3%AE%E6%B5%B7%E9%B9%BF%E5%B7%A5%E4%BD%9C%E5%AE%A4.html\":\"/Yao/myblog/SHL.html\",\"/Yao/myblog/%E8%87%AA%E6%88%91%E4%BB%8B%E7%BB%8D.html\":\"/Yao/myblog/me.html\",\"/Yao/YaoA/links/%E5%9C%A8%E7%BA%BF%E5%B7%A5%E5%85%B7.html\":\"/Yao/YaoA/links/web_tool.html\",\"/Yao/YaoA/links/%E6%94%BF%E5%BA%9C%E7%BD%91%E7%AB%99.html\":\"/Yao/YaoA/links/web_ZF.html\",\"/Yao/YaoA/links/%E7%BC%96%E7%A8%8B%E7%BD%91%E7%AB%99.html\":\"/Yao/YaoA/links/web_BC.html\",\"/Yao/YaoA/movies/%E7%94%B5%E5%BD%B1%E7%BD%91%E7%AB%99.html\":\"/Yao/YaoA/movies/movies_weblist.html\",\"/Yao/YaoA/music/QQ%E9%9F%B3%E4%B9%90%E6%AD%8C%E5%8D%95.html\":\"/Yao/YaoA/music/qq_music.html\",\"/Yao/YaoA/music/%E7%BD%91%E6%98%93%E4%BA%91%E6%AD%8C%E5%8D%95.html\":\"/Yao/YaoA/music/wyy_music.html\",\"/Yao/YaoA/music/%E9%85%B7%E7%8B%97%E6%AD%8C%E5%8D%95.html\":\"/Yao/YaoA/music/kugou_music.html\",\"/Yao/YaoA/photos/%E5%BE%AE%E8%BD%AFbing.html\":\"/Yao/YaoA/photos/bing_img_api.html\",\"/Yao/YaoA/word/%E5%B0%8F%E8%AF%B4.html\":\"/Yao/YaoA/word/word_XS.html\"}")

export const routes = Object.fromEntries([
  ["/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/index.html.js"), meta: {"t":"首页","i":"home"} }],
  ["/en/intro.html", { loader: () => import(/* webpackChunkName: "en_intro.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/intro.html.js"), meta: {"d":1728229667000,"e":"\n<p>Place your introduction and profile here.</p>\n","r":{"minutes":0.03,"words":10},"t":"Intro Page","i":"info","y":"a"} }],
  ["/en/", { loader: () => import(/* webpackChunkName: "en_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/index.html.js"), meta: {"t":"Home","i":"home"} }],
  ["/Yao/", { loader: () => import(/* webpackChunkName: "Yao_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/index.html.js"), meta: {"d":1728311364000,"r":{"minutes":0.01,"words":4},"t":"","y":"a"} }],
  ["/en/demo/disable.html", { loader: () => import(/* webpackChunkName: "en_demo_disable.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/demo/disable.html.js"), meta: {"d":1728229667000,"c":["Guide"],"g":["disable"],"e":"<p>You can disable some function and layout on the page by setting the Frontmatter of the page.</p>\n","r":{"minutes":0.28,"words":83},"t":"Disabling layout and features","i":"config","O":3,"y":"a"} }],
  ["/en/demo/encrypt.html", { loader: () => import(/* webpackChunkName: "en_demo_encrypt.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/demo/encrypt.html.js"), meta: {"d":1728229667000,"c":["Guide"],"g":["encryption"],"e":"\n<p>The actual article content.</p>\n<p>Paragraph 1 text paragraph 1 text paragraph 1 text paragraph 1 text paragraph 1 text paragraph 1 text paragraph 1 text paragraph 1 text paragraph 1 text paragraph 1 text paragraph 1 text paragraph 1 text.</p>\n<p>Paragraph 2 text paragraph 2 text paragraph 2 text paragraph 2 text paragraph 2 text paragraph 2 text paragraph 2 text paragraph 2 text paragraph 2 text paragraph 2 text paragraph 2 text paragraph 2 text paragraph 2 text paragraph 2 text.</p>","r":{"minutes":0.3,"words":90},"t":"Encryption Article","i":"lock","y":"a"} }],
  ["/en/demo/page.html", { loader: () => import(/* webpackChunkName: "en_demo_page.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/demo/page.html.js"), meta: {"a":"Ms.Hope","d":1577836800000,"l":"January 1, 2020","c":["Guide"],"g":["Page config","Guide"],"u":true,"e":"<p>Content before <code>more</code> comment is regarded as page excerpt.</p>\n","r":{"minutes":0.89,"words":268},"t":"Page Config","i":"page","O":1,"y":"a"} }],
  ["/en/demo/", { loader: () => import(/* webpackChunkName: "en_demo_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/demo/index.html.js"), meta: {"d":1728311364000,"c":["Guide"],"e":"<h2>Catalog</h2>\n<ul>\n<li>\n<p><a href=\"/Yao/en/demo/page.html\" target=\"_blank\">Page Config</a></p>\n</li>\n<li>\n<p><a href=\"/Yao/en/demo/disable.html\" target=\"_blank\">Function Disable</a></p>\n</li>\n<li>\n<p><a href=\"/Yao/en/demo/encrypt.html\" target=\"_blank\">Encryption Demo</a></p>\n</li>\n</ul>\n","r":{"minutes":0.06,"words":19},"t":"Features Demo","i":"discover","y":"a"} }],
  ["/en/posts/cherry.html", { loader: () => import(/* webpackChunkName: "en_posts_cherry.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/cherry.html.js"), meta: {"d":1641686400000,"l":"January 9, 2022","c":["Cherry"],"g":["red","small","round"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.08,"words":25},"t":"Cherry","i":"edit","y":"a"} }],
  ["/en/posts/dragonfruit.html", { loader: () => import(/* webpackChunkName: "en_posts_dragonfruit.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/dragonfruit.html.js"), meta: {"d":1641772800000,"l":"January 10, 2022","c":["Dragon Fruit","Fruit"],"g":["red","big"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.09,"words":27},"t":"Dragon Fruit","i":"edit","y":"a"} }],
  ["/en/posts/strawberry.html", { loader: () => import(/* webpackChunkName: "en_posts_strawberry.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/strawberry.html.js"), meta: {"d":1641859200000,"l":"January 11, 2022","c":["Fruit","Strawberry"],"g":["red","small"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.08,"words":25},"t":"Strawberry","i":"edit","y":"a"} }],
  ["/en/posts/tomato.html", { loader: () => import(/* webpackChunkName: "en_posts_tomato.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/tomato.html.js"), meta: {"d":1641945600000,"l":"January 12, 2022","c":["Vegetable"],"g":["red","round"],"u":true,"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.09,"words":28},"t":"Tomato","i":"edit","y":"a"} }],
  ["/Yao/myblog/", { loader: () => import(/* webpackChunkName: "Yao_myblog_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/myblog/index.html.js"), meta: {"d":729561600000,"l":"1993年2月13日","e":"\n<hr>\n","r":{"minutes":0.06,"words":19},"t":"关于","i":"favoritea","y":"a"} }],
  ["/Yao/myblog/web.html", { loader: () => import(/* webpackChunkName: "Yao_myblog_web.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/myblog/web.html.js"), meta: {"d":1728462613000,"e":"\n<h2>1、项目基本</h2>\n<p>使用框架：VuePress2.0.0 R17<br>\n开发软件：Vs Code 1.94.1<br>\n指令版本：npm 10.8.2、pnpm 9.11.0</p>\n<h2>2、指令相关</h2>\n<h3>2.1-创建VuePress命令：</h3>\n<div class=\"language-markdown line-numbers-mode\" data-highlighter=\"shiki\" data-ext=\"markdown\" data-title=\"markdown\" style=\"--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34\"><pre class=\"shiki shiki-themes one-light one-dark-pro vp-code\"><code><span class=\"line\"><span style=\"--shiki-light:#383A42;--shiki-dark:#ABB2BF\">![]npm init vuepress-theme-hope@latest Yaomi //创建项目Yaomi</span></span>\n<span class=\"line\"><span style=\"--shiki-light:#383A42;--shiki-dark:#ABB2BF\">![]npm run build //构建项目</span></span>\n<span class=\"line\"><span style=\"--shiki-light:#383A42;--shiki-dark:#ABB2BF\">![]npm run docs:clean-dev //清除缓存运行</span></span>\n<span class=\"line\"><span style=\"--shiki-light:#383A42;--shiki-dark:#ABB2BF\">![]npm init //项目初始化</span></span>\n<span class=\"line\"><span style=\"--shiki-light:#383A42;--shiki-dark:#ABB2BF\">![]npm install //安装依赖</span></span>\n<span class=\"line\"><span style=\"--shiki-light:#383A42;--shiki-dark:#ABB2BF\">![]code . //通过VS code 打开该项目</span></span></code></pre>\n<div class=\"line-numbers\" aria-hidden=\"true\" style=\"counter-reset:line-number 0\"><div class=\"line-number\"></div><div class=\"line-number\"></div><div class=\"line-number\"></div><div class=\"line-number\"></div><div class=\"line-number\"></div><div class=\"line-number\"></div></div></div>","r":{"minutes":1.41,"words":422},"t":"关于本站","i":"web","O":1,"y":"a"} }],
  ["/Yao/myblog/SHL.html", { loader: () => import(/* webpackChunkName: "Yao_myblog_SHL.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/myblog/SHL.html.js"), meta: {"d":1728488237000,"e":"\n<h2>一、工作室基本</h2>\n<p>英文名：Senhai Deer<br>\n成立时间：2023-08-08<br>\n理念：就做不一样</p>\n<h2>二、做什么</h2>\n<p>软件开发、电路设计、3D设计等</p>\n<h2>三、定制内容</h2>\n<p>您能看到的任何东西我们都支持定制</p>\n","r":{"minutes":0.25,"words":76},"t":"森海鹿工作室","i":"selfinfo","O":3,"y":"a"} }],
  ["/Yao/myblog/me.html", { loader: () => import(/* webpackChunkName: "Yao_myblog_me.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/myblog/me.html.js"), meta: {"d":1728408245000,"e":"\n<p>没什么可讲的，一个即将秃头的程序员，梦想是带领我的人民过上好日子！</p>\n","r":{"minutes":0.14,"words":42},"t":"自我介绍","i":"selfinfo","O":3,"y":"a"} }],
  ["/Yao/YaoA/", { loader: () => import(/* webpackChunkName: "Yao_YaoA_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/YaoA/index.html.js"), meta: {"d":729561600000,"l":"1993年2月13日","e":"\n<div class=\"hint-container info\">\n<p class=\"hint-container-title\">有些记忆，弥足珍贵</p>\n</div>\n<hr>\n","r":{"minutes":0.09,"words":28},"t":"收藏","i":"favoritea","y":"a"} }],
  ["/en/posts/apple/1.html", { loader: () => import(/* webpackChunkName: "en_posts_apple_1.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/apple/1.html.js"), meta: {"d":1640995200000,"l":"January 1, 2022","c":["Apple"],"g":["red","big","round"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.09,"words":26},"t":"Apple 1","i":"edit","y":"a"} }],
  ["/en/posts/apple/2.html", { loader: () => import(/* webpackChunkName: "en_posts_apple_2.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/apple/2.html.js"), meta: {"d":1641081600000,"l":"January 2, 2022","c":["Apple"],"g":["red","big","round"],"e":"\n<p>A apple article being stared.</p>\n","r":{"minutes":0.11,"words":34},"t":"Apple 2","i":"edit","y":"a"} }],
  ["/en/posts/apple/3.html", { loader: () => import(/* webpackChunkName: "en_posts_apple_3.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/apple/3.html.js"), meta: {"d":1641168000000,"l":"January 3, 2022","c":["Apple","Fruit"],"g":["red","big","round"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.09,"words":27},"t":"Apple 3","i":"edit","y":"a"} }],
  ["/en/posts/apple/4.html", { loader: () => import(/* webpackChunkName: "en_posts_apple_4.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/apple/4.html.js"), meta: {"d":1641254400000,"l":"January 4, 2022","c":["Apple","Fruit"],"g":["red","big","round"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.09,"words":27},"t":"Apple 4","i":"edit","y":"a"} }],
  ["/en/posts/banana/1.html", { loader: () => import(/* webpackChunkName: "en_posts_banana_1.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/banana/1.html.js"), meta: {"d":1641340800000,"l":"January 5, 2022","c":["Banana","Fruit"],"g":["yellow","curly","long"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.09,"words":27},"t":"Banana 1","i":"edit","y":"a"} }],
  ["/en/posts/banana/2.html", { loader: () => import(/* webpackChunkName: "en_posts_banana_2.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/banana/2.html.js"), meta: {"d":1641427200000,"l":"January 6, 2022","c":["Banana","Fruit"],"g":["yellow","curly","long"],"e":"\n<p>A banana article being stared with number <code>10</code>.</p>\n","r":{"minutes":0.13,"words":39},"t":"Banana 2","i":"edit","y":"a"} }],
  ["/en/posts/banana/3.html", { loader: () => import(/* webpackChunkName: "en_posts_banana_3.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/banana/3.html.js"), meta: {"d":1641513600000,"l":"January 7, 2022","c":["Banana"],"g":["yellow","curly","long"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.09,"words":26},"t":"Banana 3","i":"edit","y":"a"} }],
  ["/en/posts/banana/4.html", { loader: () => import(/* webpackChunkName: "en_posts_banana_4.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/banana/4.html.js"), meta: {"d":1641600000000,"l":"January 8, 2022","c":["Banana"],"g":["yellow","curly","long"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.09,"words":26},"t":"Banana 4","i":"edit","y":"a"} }],
  ["/Yao/YaoA/links/", { loader: () => import(/* webpackChunkName: "Yao_YaoA_links_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/YaoA/links/index.html.js"), meta: {"d":1728518400000,"l":"2024年10月10日","e":"\n","r":{"minutes":0.06,"words":19},"t":"链接","i":"link","y":"a"} }],
  ["/Yao/YaoA/links/web_tool.html", { loader: () => import(/* webpackChunkName: "Yao_YaoA_links_web_tool.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/YaoA/links/web_tool.html.js"), meta: {"d":1728488237000,"e":"\n","r":{"minutes":0.35,"words":106},"t":"在线工具","i":"gongju","y":"a"} }],
  ["/Yao/YaoA/links/web_ZF.html", { loader: () => import(/* webpackChunkName: "Yao_YaoA_links_web_ZF.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/YaoA/links/web_ZF.html.js"), meta: {"d":1728488237000,"e":"\n","r":{"minutes":0.3,"words":91},"t":"政府网站","i":"youlian","y":"a"} }],
  ["/Yao/YaoA/links/web_BC.html", { loader: () => import(/* webpackChunkName: "Yao_YaoA_links_web_BC.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/YaoA/links/web_BC.html.js"), meta: {"d":1728488237000,"e":"\n","r":{"minutes":0.37,"words":111},"t":"编程工具","i":"docwenjian","y":"a"} }],
  ["/Yao/YaoA/movies/", { loader: () => import(/* webpackChunkName: "Yao_YaoA_movies_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/YaoA/movies/index.html.js"), meta: {"d":1728518400000,"l":"2024年10月10日","e":"\n<hr>\n","r":{"minutes":0.06,"words":19},"t":"影视","i":"movie","y":"a"} }],
  ["/Yao/YaoA/movies/movies_weblist.html", { loader: () => import(/* webpackChunkName: "Yao_YaoA_movies_movies_weblist.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/YaoA/movies/movies_weblist.html.js"), meta: {"e":"\n","r":{"minutes":0.3,"words":91},"t":"电影网站","y":"a"} }],
  ["/Yao/YaoA/music/qq_music.html", { loader: () => import(/* webpackChunkName: "Yao_YaoA_music_qq_music.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/YaoA/music/qq_music.html.js"), meta: {"d":1728311364000,"e":"\n<h2>我喜欢</h2>\n<iframe frameborder=\"no\" border=\"0\" marginwidth=\"0\" marginheight=\"0\" width=\"100%\" height=\"550\" src=\"https://m.kugou.com/songlist/gcid_3z6t6yn5z12z054/?src_cid=3z6t6yn5z12z054&amp;uid=358949085&amp;chl=message&amp;iszlist=1\"></iframe>\n<h2>我收藏</h2>\n<iframe frameborder=\"no\" border=\"0\" marginwidth=\"0\" marginheight=\"0\" width=\"100%\" height=\"550\" src=\"//m.kugou.com/songlist/gcid_3z6t6yn5z12z054/?src_cid=3z6t6yn5z12z054&amp;auto=0&amp;height=430\"></iframe>","r":{"minutes":0.2,"words":60},"t":"QQ音乐歌单","y":"a"} }],
  ["/Yao/YaoA/music/", { loader: () => import(/* webpackChunkName: "Yao_YaoA_music_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/YaoA/music/index.html.js"), meta: {"d":729561600000,"l":"1993年2月13日","e":"\n","r":{"minutes":0.06,"words":19},"t":"音乐","i":"music","y":"a"} }],
  ["/Yao/YaoA/music/wyy_music.html", { loader: () => import(/* webpackChunkName: "Yao_YaoA_music_wyy_music.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/YaoA/music/wyy_music.html.js"), meta: {"d":1728311364000,"e":"\n<h2>我喜欢</h2>\n<iframe frameborder=\"no\" border=\"0\" marginwidth=\"0\" marginheight=\"0\" width=\"100%\" height=\"500\" src=\"//music.163.com/outchain/player?type=0&amp;id=639419756&amp;auto=0&amp;height=430\"></iframe>\n<h2>我收藏</h2>\n<iframe frameborder=\"no\" border=\"0\" marginwidth=\"0\" marginheight=\"0\" width=\"100%\" height=\"500\" src=\"//music.163.com/outchain/player?type=0&amp;id=6781242751&amp;auto=0&amp;height=430\"></iframe>","r":{"minutes":0.2,"words":61},"t":"网易云歌单","y":"a"} }],
  ["/Yao/YaoA/music/kugou_music.html", { loader: () => import(/* webpackChunkName: "Yao_YaoA_music_kugou_music.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/YaoA/music/kugou_music.html.js"), meta: {"d":1728311364000,"e":"\n<h2>我喜欢</h2>\n<iframe frameborder=\"no\" border=\"0\" marginwidth=\"0\" marginheight=\"0\" width=\"100%\" height=\"550\" src=\"https://m.kugou.com/songlist/gcid_3z6t6yn5z3z084/?src_cid=3z6t6yn5z3z084&amp;uid=358949085&amp;chl=message&amp;cover=http://imge.kugou.com/stdmusic/20220811/20220811194205341403.jpg&amp;iszlist=1\"></iframe>","r":{"minutes":0.25,"words":75},"t":"酷狗歌单","y":"a"} }],
  ["/Yao/YaoA/photos/", { loader: () => import(/* webpackChunkName: "Yao_YaoA_photos_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/YaoA/photos/index.html.js"), meta: {"d":1728518400000,"l":"2024年10月10日","e":"\n<div class=\"hint-container info\">\n<p class=\"hint-container-title\">照片让一瞬间变得永恒！</p>\n</div>\n<hr>\n","r":{"minutes":0.1,"words":30},"t":"相册","i":"bing","y":"a"} }],
  ["/Yao/YaoA/photos/bing_img_api.html", { loader: () => import(/* webpackChunkName: "Yao_YaoA_photos_bing_img_api.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/YaoA/photos/bing_img_api.html.js"), meta: {"d":1728311364000,"e":"\n<p><img src=\"//file.mo7.cc/api/public/bz?idx=1\" alt=\"\" loading=\"lazy\"><br>\n<img src=\"//file.mo7.cc/api/public/bz?idx=3\" alt=\"\" loading=\"lazy\"><br>\n<img src=\"//file.mo7.cc/api/public/bz\" alt=\"\" loading=\"lazy\"></p>\n","r":{"minutes":0.06,"words":18},"t":"必应每日壁纸 api","i":"bing","y":"a"} }],
  ["/Yao/YaoA/word/", { loader: () => import(/* webpackChunkName: "Yao_YaoA_word_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/YaoA/word/index.html.js"), meta: {"d":729561600000,"l":"1993年2月13日","e":"\n","r":{"minutes":0.06,"words":19},"t":"文字","i":"bing","y":"a"} }],
  ["/Yao/YaoA/word/word_XS.html", { loader: () => import(/* webpackChunkName: "Yao_YaoA_word_word_XS.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/YaoA/word/word_XS.html.js"), meta: {"d":1728488237000,"e":"\n","r":{"minutes":0.25,"words":76},"t":"诗词小说","i":"bing","y":"a"} }],
  ["/404.html", { loader: () => import(/* webpackChunkName: "404.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/404.html.js"), meta: {"t":""} }],
  ["/en/posts/", { loader: () => import(/* webpackChunkName: "en_posts_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/index.html.js"), meta: {"t":"Posts"} }],
  ["/en/posts/apple/", { loader: () => import(/* webpackChunkName: "en_posts_apple_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/apple/index.html.js"), meta: {"t":"Apple"} }],
  ["/en/posts/banana/", { loader: () => import(/* webpackChunkName: "en_posts_banana_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/banana/index.html.js"), meta: {"t":"Banana"} }],
  ["/en/category/", { loader: () => import(/* webpackChunkName: "en_category_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/category/index.html.js"), meta: {"t":"Category","I":false} }],
  ["/en/category/guide/", { loader: () => import(/* webpackChunkName: "en_category_guide_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/category/guide/index.html.js"), meta: {"t":"Guide Category","I":false} }],
  ["/en/category/cherry/", { loader: () => import(/* webpackChunkName: "en_category_cherry_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/category/cherry/index.html.js"), meta: {"t":"Cherry Category","I":false} }],
  ["/en/category/dragon-fruit/", { loader: () => import(/* webpackChunkName: "en_category_dragon-fruit_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/category/dragon-fruit/index.html.js"), meta: {"t":"Dragon Fruit Category","I":false} }],
  ["/en/category/fruit/", { loader: () => import(/* webpackChunkName: "en_category_fruit_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/category/fruit/index.html.js"), meta: {"t":"Fruit Category","I":false} }],
  ["/en/category/strawberry/", { loader: () => import(/* webpackChunkName: "en_category_strawberry_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/category/strawberry/index.html.js"), meta: {"t":"Strawberry Category","I":false} }],
  ["/en/category/vegetable/", { loader: () => import(/* webpackChunkName: "en_category_vegetable_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/category/vegetable/index.html.js"), meta: {"t":"Vegetable Category","I":false} }],
  ["/en/category/apple/", { loader: () => import(/* webpackChunkName: "en_category_apple_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/category/apple/index.html.js"), meta: {"t":"Apple Category","I":false} }],
  ["/en/category/banana/", { loader: () => import(/* webpackChunkName: "en_category_banana_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/category/banana/index.html.js"), meta: {"t":"Banana Category","I":false} }],
  ["/category/", { loader: () => import(/* webpackChunkName: "category_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/category/index.html.js"), meta: {"t":"分类","I":false} }],
  ["/en/tag/", { loader: () => import(/* webpackChunkName: "en_tag_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/tag/index.html.js"), meta: {"t":"Tag","I":false} }],
  ["/en/tag/disable/", { loader: () => import(/* webpackChunkName: "en_tag_disable_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/tag/disable/index.html.js"), meta: {"t":"Tag: disable","I":false} }],
  ["/en/tag/encryption/", { loader: () => import(/* webpackChunkName: "en_tag_encryption_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/tag/encryption/index.html.js"), meta: {"t":"Tag: encryption","I":false} }],
  ["/en/tag/page-config/", { loader: () => import(/* webpackChunkName: "en_tag_page-config_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/tag/page-config/index.html.js"), meta: {"t":"Tag: Page config","I":false} }],
  ["/en/tag/guide/", { loader: () => import(/* webpackChunkName: "en_tag_guide_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/tag/guide/index.html.js"), meta: {"t":"Tag: Guide","I":false} }],
  ["/en/tag/red/", { loader: () => import(/* webpackChunkName: "en_tag_red_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/tag/red/index.html.js"), meta: {"t":"Tag: red","I":false} }],
  ["/en/tag/small/", { loader: () => import(/* webpackChunkName: "en_tag_small_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/tag/small/index.html.js"), meta: {"t":"Tag: small","I":false} }],
  ["/en/tag/round/", { loader: () => import(/* webpackChunkName: "en_tag_round_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/tag/round/index.html.js"), meta: {"t":"Tag: round","I":false} }],
  ["/en/tag/big/", { loader: () => import(/* webpackChunkName: "en_tag_big_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/tag/big/index.html.js"), meta: {"t":"Tag: big","I":false} }],
  ["/en/tag/yellow/", { loader: () => import(/* webpackChunkName: "en_tag_yellow_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/tag/yellow/index.html.js"), meta: {"t":"Tag: yellow","I":false} }],
  ["/en/tag/curly/", { loader: () => import(/* webpackChunkName: "en_tag_curly_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/tag/curly/index.html.js"), meta: {"t":"Tag: curly","I":false} }],
  ["/en/tag/long/", { loader: () => import(/* webpackChunkName: "en_tag_long_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/tag/long/index.html.js"), meta: {"t":"Tag: long","I":false} }],
  ["/tag/", { loader: () => import(/* webpackChunkName: "tag_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/tag/index.html.js"), meta: {"t":"标签","I":false} }],
  ["/en/article/", { loader: () => import(/* webpackChunkName: "en_article_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/article/index.html.js"), meta: {"t":"Articles","I":false} }],
  ["/article/", { loader: () => import(/* webpackChunkName: "article_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/article/index.html.js"), meta: {"t":"文章","I":false} }],
  ["/en/star/", { loader: () => import(/* webpackChunkName: "en_star_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/star/index.html.js"), meta: {"t":"Star","I":false} }],
  ["/star/", { loader: () => import(/* webpackChunkName: "star_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/star/index.html.js"), meta: {"t":"星标","I":false} }],
  ["/en/timeline/", { loader: () => import(/* webpackChunkName: "en_timeline_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/timeline/index.html.js"), meta: {"t":"Timeline","I":false} }],
  ["/timeline/", { loader: () => import(/* webpackChunkName: "timeline_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/timeline/index.html.js"), meta: {"t":"时间轴","I":false} }],
]);

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateRoutes) {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
  }
  if (__VUE_HMR_RUNTIME__.updateRedirects) {
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ routes, redirects }) => {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  })
}
