export const redirects = JSON.parse("{\"/Yao/myblog/%E5%85%B3%E4%BA%8E%E6%9C%AC%E7%AB%99.html\":\"/Yao/myblog/website.html\",\"/Yao/myblog/%E5%A7%9A%E7%9A%84%E4%BB%8B%E7%BB%8D.html\":\"/Yao/myblog/me.html\",\"/Yao/Yaoa_zyk/movies/%E9%98%BF%E7%94%98%E6%AD%A3%E4%BC%A0.html\":\"/Yao/Yaoa_zyk/ForrestGump.html\",\"/Yao/Yaoa_zyk/music/QQ%E9%9F%B3%E4%B9%90%E6%AD%8C%E5%8D%95.html\":\"/Yao/Yaoa_zyk/music/qq_music.html\",\"/Yao/Yaoa_zyk/music/%E7%BD%91%E6%98%93%E4%BA%91%E6%AD%8C%E5%8D%95.html\":\"/Yao/Yaoa_zyk/music/music163_favorite.html\",\"/Yao/Yaoa_zyk/music/%E9%85%B7%E7%8B%97%E6%AD%8C%E5%8D%95.html\":\"/Yao/Yaoa_zyk/music/kugou_music.html\"}")

export const routes = Object.fromEntries([
  ["/", { loader: () => import(/* webpackChunkName: "index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/index.html.js"), meta: {"t":"首页","i":"home"} }],
  ["/en/intro.html", { loader: () => import(/* webpackChunkName: "en_intro.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/intro.html.js"), meta: {"d":1728229667000,"e":"\n<p>Place your introduction and profile here.</p>\n","r":{"minutes":0.03,"words":10},"t":"Intro Page","i":"info","y":"a"} }],
  ["/en/", { loader: () => import(/* webpackChunkName: "en_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/index.html.js"), meta: {"t":"Home","i":"home"} }],
  ["/Yao/", { loader: () => import(/* webpackChunkName: "Yao_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/index.html.js"), meta: {"d":1728311364000,"r":{"minutes":0.01,"words":4},"t":"","y":"a"} }],
  ["/en/demo/disable.html", { loader: () => import(/* webpackChunkName: "en_demo_disable.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/demo/disable.html.js"), meta: {"d":1728229667000,"c":["Guide"],"g":["disable"],"e":"<p>You can disable some function and layout on the page by setting the Frontmatter of the page.</p>\n","r":{"minutes":0.28,"words":83},"t":"Disabling layout and features","i":"config","O":3,"y":"a"} }],
  ["/en/demo/encrypt.html", { loader: () => import(/* webpackChunkName: "en_demo_encrypt.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/demo/encrypt.html.js"), meta: {"d":1728229667000,"c":["Guide"],"g":["encryption"],"e":"\n<p>The actual article content.</p>\n<p>Paragraph 1 text paragraph 1 text paragraph 1 text paragraph 1 text paragraph 1 text paragraph 1 text paragraph 1 text paragraph 1 text paragraph 1 text paragraph 1 text paragraph 1 text paragraph 1 text.</p>\n<p>Paragraph 2 text paragraph 2 text paragraph 2 text paragraph 2 text paragraph 2 text paragraph 2 text paragraph 2 text paragraph 2 text paragraph 2 text paragraph 2 text paragraph 2 text paragraph 2 text paragraph 2 text paragraph 2 text.</p>","r":{"minutes":0.3,"words":90},"t":"Encryption Article","i":"lock","y":"a"} }],
  ["/en/demo/page.html", { loader: () => import(/* webpackChunkName: "en_demo_page.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/demo/page.html.js"), meta: {"a":"Ms.Hope","d":1577836800000,"l":"January 1, 2020","c":["Guide"],"g":["Page config","Guide"],"u":true,"e":"<p>Content before <code>more</code> comment is regarded as page excerpt.</p>\n","r":{"minutes":0.89,"words":268},"t":"Page Config","i":"page","O":1,"y":"a"} }],
  ["/en/demo/", { loader: () => import(/* webpackChunkName: "en_demo_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/demo/index.html.js"), meta: {"d":1728311364000,"c":["Guide"],"e":"<h2>Catalog</h2>\n<ul>\n<li>\n<p><a href=\"/Yao/en/demo/page.html\" target=\"_blank\">Page Config</a></p>\n</li>\n<li>\n<p><a href=\"/Yao/en/demo/disable.html\" target=\"_blank\">Function Disable</a></p>\n</li>\n<li>\n<p><a href=\"/Yao/en/demo/encrypt.html\" target=\"_blank\">Encryption Demo</a></p>\n</li>\n</ul>\n","r":{"minutes":0.06,"words":19},"t":"Features Demo","i":"discover","y":"a"} }],
  ["/en/posts/cherry.html", { loader: () => import(/* webpackChunkName: "en_posts_cherry.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/cherry.html.js"), meta: {"d":1641686400000,"l":"January 9, 2022","c":["Cherry"],"g":["red","small","round"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.08,"words":25},"t":"Cherry","i":"edit","y":"a"} }],
  ["/en/posts/dragonfruit.html", { loader: () => import(/* webpackChunkName: "en_posts_dragonfruit.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/dragonfruit.html.js"), meta: {"d":1641772800000,"l":"January 10, 2022","c":["Dragon Fruit","Fruit"],"g":["red","big"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.09,"words":27},"t":"Dragon Fruit","i":"edit","y":"a"} }],
  ["/en/posts/strawberry.html", { loader: () => import(/* webpackChunkName: "en_posts_strawberry.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/strawberry.html.js"), meta: {"d":1641859200000,"l":"January 11, 2022","c":["Fruit","Strawberry"],"g":["red","small"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.08,"words":25},"t":"Strawberry","i":"edit","y":"a"} }],
  ["/en/posts/tomato.html", { loader: () => import(/* webpackChunkName: "en_posts_tomato.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/tomato.html.js"), meta: {"d":1641945600000,"l":"January 12, 2022","c":["Vegetable"],"g":["red","round"],"u":true,"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.09,"words":28},"t":"Tomato","i":"edit","y":"a"} }],
  ["/Yao/myblog/", { loader: () => import(/* webpackChunkName: "Yao_myblog_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/myblog/index.html.js"), meta: {"d":729561600000,"l":"1993年2月13日","e":"\n<div class=\"hint-container info\">\n<p class=\"hint-container-title\">有些记忆，弥足珍贵</p>\n</div>\n<hr>\n","r":{"minutes":0.09,"words":28},"t":"收藏","i":"favoritea","y":"a"} }],
  ["/Yao/myblog/website.html", { loader: () => import(/* webpackChunkName: "Yao_myblog_website.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/myblog/website.html.js"), meta: {"d":1728462613000,"e":"\n<h2>前言</h2>\n","r":{"minutes":0.06,"words":17},"t":"关于本站 Yao测试","i":"web","O":1,"y":"a"} }],
  ["/Yao/myblog/me.html", { loader: () => import(/* webpackChunkName: "Yao_myblog_me.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/myblog/me.html.js"), meta: {"d":1728408245000,"e":"\n","r":{"minutes":0.04,"words":13},"t":"关于我 测试","i":"selfinfo","O":3,"y":"a"} }],
  ["/Yao/Yaoa_zyk/", { loader: () => import(/* webpackChunkName: "Yao_Yaoa_zyk_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/Yaoa_zyk/index.html.js"), meta: {"d":729561600000,"l":"1993年2月13日","e":"\n<div class=\"hint-container info\">\n<p class=\"hint-container-title\">有些记忆，弥足珍贵</p>\n</div>\n<hr>\n","r":{"minutes":0.09,"words":28},"t":"收藏","i":"favoritea","y":"a"} }],
  ["/en/posts/apple/1.html", { loader: () => import(/* webpackChunkName: "en_posts_apple_1.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/apple/1.html.js"), meta: {"d":1640995200000,"l":"January 1, 2022","c":["Apple"],"g":["red","big","round"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.09,"words":26},"t":"Apple 1","i":"edit","y":"a"} }],
  ["/en/posts/apple/2.html", { loader: () => import(/* webpackChunkName: "en_posts_apple_2.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/apple/2.html.js"), meta: {"d":1641081600000,"l":"January 2, 2022","c":["Apple"],"g":["red","big","round"],"e":"\n<p>A apple article being stared.</p>\n","r":{"minutes":0.11,"words":34},"t":"Apple 2","i":"edit","y":"a"} }],
  ["/en/posts/apple/3.html", { loader: () => import(/* webpackChunkName: "en_posts_apple_3.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/apple/3.html.js"), meta: {"d":1641168000000,"l":"January 3, 2022","c":["Apple","Fruit"],"g":["red","big","round"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.09,"words":27},"t":"Apple 3","i":"edit","y":"a"} }],
  ["/en/posts/apple/4.html", { loader: () => import(/* webpackChunkName: "en_posts_apple_4.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/apple/4.html.js"), meta: {"d":1641254400000,"l":"January 4, 2022","c":["Apple","Fruit"],"g":["red","big","round"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.09,"words":27},"t":"Apple 4","i":"edit","y":"a"} }],
  ["/en/posts/banana/1.html", { loader: () => import(/* webpackChunkName: "en_posts_banana_1.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/banana/1.html.js"), meta: {"d":1641340800000,"l":"January 5, 2022","c":["Banana","Fruit"],"g":["yellow","curly","long"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.09,"words":27},"t":"Banana 1","i":"edit","y":"a"} }],
  ["/en/posts/banana/2.html", { loader: () => import(/* webpackChunkName: "en_posts_banana_2.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/banana/2.html.js"), meta: {"d":1641427200000,"l":"January 6, 2022","c":["Banana","Fruit"],"g":["yellow","curly","long"],"e":"\n<p>A banana article being stared with number <code>10</code>.</p>\n","r":{"minutes":0.13,"words":39},"t":"Banana 2","i":"edit","y":"a"} }],
  ["/en/posts/banana/3.html", { loader: () => import(/* webpackChunkName: "en_posts_banana_3.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/banana/3.html.js"), meta: {"d":1641513600000,"l":"January 7, 2022","c":["Banana"],"g":["yellow","curly","long"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.09,"words":26},"t":"Banana 3","i":"edit","y":"a"} }],
  ["/en/posts/banana/4.html", { loader: () => import(/* webpackChunkName: "en_posts_banana_4.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/banana/4.html.js"), meta: {"d":1641600000000,"l":"January 8, 2022","c":["Banana"],"g":["yellow","curly","long"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.09,"words":26},"t":"Banana 4","i":"edit","y":"a"} }],
  ["/Yao/Yaoa_zyk/movies/", { loader: () => import(/* webpackChunkName: "Yao_Yaoa_zyk_movies_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/Yaoa_zyk/movies/index.html.js"), meta: {"d":729561600000,"l":"1993年2月13日","e":"\n<div class=\"hint-container info\">\n<p class=\"hint-container-title\">『 生活就像一盒巧克力 』</p>\n</div>\n<hr>\n","r":{"minutes":0.1,"words":29},"t":"影视","i":"movie","y":"a"} }],
  ["/Yao/Yaoa_zyk/ForrestGump.html", { loader: () => import(/* webpackChunkName: "Yao_Yaoa_zyk_ForrestGump.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/Yaoa_zyk/ForrestGump.html.js"), meta: {"d":1728311364000,"e":"\n<p>《阿甘正传》是由罗伯特·泽米吉斯执导的电影，由汤姆·汉克斯、罗宾·怀特等人主演，于 1994 年 7 月 6 日在美国上映。</p>\n<p>电影改编自美国作家温斯顿·格鲁姆于 1986 年出版的同名小说，描绘了先天智障的小镇男孩福瑞斯特·甘自强不息，最终“傻人有傻福”地得到上天眷顾，在多个领域创造奇迹的励志故事 [1] 。电影上映后，于 1995 年获得奥斯卡最佳影片奖、最佳男主角奖、最佳导演奖等 6 项大奖 。</p>\n<p>2014 年 9 月 5 日，在该片上映 20 周年之际，《阿甘正传》IMAX 版本开始在全美上映</p>\n","r":{"minutes":0.63,"words":189},"t":"阿甘正传","y":"a"} }],
  ["/Yao/Yaoa_zyk/music/qq_music.html", { loader: () => import(/* webpackChunkName: "Yao_Yaoa_zyk_music_qq_music.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/Yaoa_zyk/music/qq_music.html.js"), meta: {"d":1728311364000,"e":"\n<!--<iframe frameborder=\"no\" border=\"0\" marginwidth=\"0\" marginheight=\"0\" width=100% height=550 src=\"//music.163.com/outchain/player?type=0&id=8056247134&auto=0&height=430\"></iframe>\n-->\n<iframe frameborder=\"no\" border=\"0\" marginwidth=\"0\" marginheight=\"0\" width=\"100%\" height=\"550\" src=\"//music.163.com/outchain/player?type=0&amp;id=639419756&amp;auto=0&amp;height=430\"></iframe>","r":{"minutes":0.19,"words":56},"t":"网易云歌单2","y":"a"} }],
  ["/Yao/Yaoa_zyk/music/", { loader: () => import(/* webpackChunkName: "Yao_Yaoa_zyk_music_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/Yaoa_zyk/music/index.html.js"), meta: {"d":729561600000,"l":"1993年2月13日","e":"\n<div class=\"hint-container info\">\n<p class=\"hint-container-title\">单曲循环一整天</p>\n</div>\n<hr>\n","r":{"minutes":0.09,"words":27},"t":"音乐","i":"music","y":"a"} }],
  ["/Yao/Yaoa_zyk/music/music163_favorite.html", { loader: () => import(/* webpackChunkName: "Yao_Yaoa_zyk_music_music163_favorite.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/Yaoa_zyk/music/music163_favorite.html.js"), meta: {"d":1728311364000,"e":"\n<!--<iframe frameborder=\"no\" border=\"0\" marginwidth=\"0\" marginheight=\"0\" width=100% height=550 src=\"//music.163.com/outchain/player?type=0&id=8056247134&auto=0&height=430\"></iframe>\n-->\n<iframe frameborder=\"no\" border=\"0\" marginwidth=\"0\" marginheight=\"0\" width=\"100%\" height=\"550\" src=\"//music.163.com/outchain/player?type=0&amp;id=639419756&amp;auto=0&amp;height=430\"></iframe>","r":{"minutes":0.18,"words":55},"t":"网易云歌单","y":"a"} }],
  ["/Yao/Yaoa_zyk/music/kugou_music.html", { loader: () => import(/* webpackChunkName: "Yao_Yaoa_zyk_music_kugou_music.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/Yao/Yaoa_zyk/music/kugou_music.html.js"), meta: {"d":1728311364000,"e":"\n<!--<iframe frameborder=\"no\" border=\"0\" marginwidth=\"0\" marginheight=\"0\" width=100% height=550 src=\"//music.163.com/outchain/player?type=0&id=8056247134&auto=0&height=430\"></iframe>\n-->\n<iframe frameborder=\"no\" border=\"0\" marginwidth=\"0\" marginheight=\"0\" width=\"100%\" height=\"550\" src=\"//music.163.com/outchain/player?type=0&amp;id=639419756&amp;auto=0&amp;height=430\"></iframe>","r":{"minutes":0.18,"words":55},"t":"酷狗歌单1","y":"a"} }],
  ["/404.html", { loader: () => import(/* webpackChunkName: "404.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/404.html.js"), meta: {"t":""} }],
  ["/en/posts/", { loader: () => import(/* webpackChunkName: "en_posts_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/index.html.js"), meta: {"t":"Posts"} }],
  ["/en/posts/apple/", { loader: () => import(/* webpackChunkName: "en_posts_apple_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/apple/index.html.js"), meta: {"t":"Apple"} }],
  ["/en/posts/banana/", { loader: () => import(/* webpackChunkName: "en_posts_banana_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/posts/banana/index.html.js"), meta: {"t":"Banana"} }],
  ["/en/category/", { loader: () => import(/* webpackChunkName: "en_category_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/category/index.html.js"), meta: {"t":"Category","I":false} }],
  ["/en/category/guide/", { loader: () => import(/* webpackChunkName: "en_category_guide_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/category/guide/index.html.js"), meta: {"t":"Guide Category","I":false} }],
  ["/en/category/cherry/", { loader: () => import(/* webpackChunkName: "en_category_cherry_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/category/cherry/index.html.js"), meta: {"t":"Cherry Category","I":false} }],
  ["/en/category/dragon-fruit/", { loader: () => import(/* webpackChunkName: "en_category_dragon-fruit_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/category/dragon-fruit/index.html.js"), meta: {"t":"Dragon Fruit Category","I":false} }],
  ["/en/category/fruit/", { loader: () => import(/* webpackChunkName: "en_category_fruit_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/category/fruit/index.html.js"), meta: {"t":"Fruit Category","I":false} }],
  ["/en/category/strawberry/", { loader: () => import(/* webpackChunkName: "en_category_strawberry_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/category/strawberry/index.html.js"), meta: {"t":"Strawberry Category","I":false} }],
  ["/en/category/vegetable/", { loader: () => import(/* webpackChunkName: "en_category_vegetable_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/category/vegetable/index.html.js"), meta: {"t":"Vegetable Category","I":false} }],
  ["/en/category/apple/", { loader: () => import(/* webpackChunkName: "en_category_apple_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/category/apple/index.html.js"), meta: {"t":"Apple Category","I":false} }],
  ["/en/category/banana/", { loader: () => import(/* webpackChunkName: "en_category_banana_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/category/banana/index.html.js"), meta: {"t":"Banana Category","I":false} }],
  ["/category/", { loader: () => import(/* webpackChunkName: "category_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/category/index.html.js"), meta: {"t":"分类","I":false} }],
  ["/en/tag/", { loader: () => import(/* webpackChunkName: "en_tag_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/tag/index.html.js"), meta: {"t":"Tag","I":false} }],
  ["/en/tag/disable/", { loader: () => import(/* webpackChunkName: "en_tag_disable_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/tag/disable/index.html.js"), meta: {"t":"Tag: disable","I":false} }],
  ["/en/tag/encryption/", { loader: () => import(/* webpackChunkName: "en_tag_encryption_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/tag/encryption/index.html.js"), meta: {"t":"Tag: encryption","I":false} }],
  ["/en/tag/page-config/", { loader: () => import(/* webpackChunkName: "en_tag_page-config_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/tag/page-config/index.html.js"), meta: {"t":"Tag: Page config","I":false} }],
  ["/en/tag/guide/", { loader: () => import(/* webpackChunkName: "en_tag_guide_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/tag/guide/index.html.js"), meta: {"t":"Tag: Guide","I":false} }],
  ["/en/tag/red/", { loader: () => import(/* webpackChunkName: "en_tag_red_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/tag/red/index.html.js"), meta: {"t":"Tag: red","I":false} }],
  ["/en/tag/small/", { loader: () => import(/* webpackChunkName: "en_tag_small_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/tag/small/index.html.js"), meta: {"t":"Tag: small","I":false} }],
  ["/en/tag/round/", { loader: () => import(/* webpackChunkName: "en_tag_round_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/tag/round/index.html.js"), meta: {"t":"Tag: round","I":false} }],
  ["/en/tag/big/", { loader: () => import(/* webpackChunkName: "en_tag_big_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/tag/big/index.html.js"), meta: {"t":"Tag: big","I":false} }],
  ["/en/tag/yellow/", { loader: () => import(/* webpackChunkName: "en_tag_yellow_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/tag/yellow/index.html.js"), meta: {"t":"Tag: yellow","I":false} }],
  ["/en/tag/curly/", { loader: () => import(/* webpackChunkName: "en_tag_curly_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/tag/curly/index.html.js"), meta: {"t":"Tag: curly","I":false} }],
  ["/en/tag/long/", { loader: () => import(/* webpackChunkName: "en_tag_long_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/tag/long/index.html.js"), meta: {"t":"Tag: long","I":false} }],
  ["/tag/", { loader: () => import(/* webpackChunkName: "tag_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/tag/index.html.js"), meta: {"t":"标签","I":false} }],
  ["/en/article/", { loader: () => import(/* webpackChunkName: "en_article_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/article/index.html.js"), meta: {"t":"Articles","I":false} }],
  ["/article/", { loader: () => import(/* webpackChunkName: "article_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/article/index.html.js"), meta: {"t":"文章","I":false} }],
  ["/en/star/", { loader: () => import(/* webpackChunkName: "en_star_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/star/index.html.js"), meta: {"t":"Star","I":false} }],
  ["/star/", { loader: () => import(/* webpackChunkName: "star_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/star/index.html.js"), meta: {"t":"星标","I":false} }],
  ["/en/timeline/", { loader: () => import(/* webpackChunkName: "en_timeline_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/en/timeline/index.html.js"), meta: {"t":"Timeline","I":false} }],
  ["/timeline/", { loader: () => import(/* webpackChunkName: "timeline_index.html" */"D:/node/Yaoweb5/.vscode/.vp-temp/pages/timeline/index.html.js"), meta: {"t":"时间轴","I":false} }],
]);

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateRoutes) {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
  }
  if (__VUE_HMR_RUNTIME__.updateRedirects) {
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ routes, redirects }) => {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  })
}
