import comp from "D:/node/Yaoweb5/.vscode/.vp-temp/pages/tutorial/vuepress-hope/img-preview.html.vue"
const data = JSON.parse("{\"path\":\"/tutorial/vuepress-hope/img-preview.html\",\"title\":\"10.图片预览插件\",\"lang\":\"zh-CN\",\"frontmatter\":{\"category\":[\"博客搭建教程\"],\"tag\":[\"教程\",\"工具\"],\"order\":10,\"permalink\":\"/tutorial/vuepress-hope/img-preview.html\",\"description\":\"10.图片预览插件 相关信息 觉得官方的图片预览插件点一下放大，点一下缩小太难用了，于是自己重新开发了一个图片预览插件。 【可完美适配移动端】 注意：得先在配置文件中禁用 vuepress 的图片预览。 plugins.photoSwipe: false 该插件在 VuePress 中使用的方式如下: 第一步： 导入插件源码 插件源码如下(可直接复制使...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://yaoabcde.github.io/Yao/Yao/tutorial/vuepress-hope/img-preview.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"YAO\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"10.图片预览插件\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"10.图片预览插件 相关信息 觉得官方的图片预览插件点一下放大，点一下缩小太难用了，于是自己重新开发了一个图片预览插件。 【可完美适配移动端】 注意：得先在配置文件中禁用 vuepress 的图片预览。 plugins.photoSwipe: false 该插件在 VuePress 中使用的方式如下: 第一步： 导入插件源码 插件源码如下(可直接复制使...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2024-10-09T09:22:35.000Z\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"教程\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"工具\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2024-10-09T09:22:35.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"10.图片预览插件\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":\\\"2024-10-09T09:22:35.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Yao\\\",\\\"url\\\":\\\"https://baidu.com\\\",\\\"email\\\":\\\"1964877312@qq.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"第一步： 导入插件源码\",\"slug\":\"第一步-导入插件源码\",\"link\":\"#第一步-导入插件源码\",\"children\":[]},{\"level\":2,\"title\":\"第二步：在 .vuepress/client.ts 中全局引入该插件\",\"slug\":\"第二步-在-vuepress-client-ts-中全局引入该插件\",\"link\":\"#第二步-在-vuepress-client-ts-中全局引入该插件\",\"children\":[]},{\"level\":2,\"title\":\"最终效果如下\",\"slug\":\"最终效果如下\",\"link\":\"#最终效果如下\",\"children\":[]}],\"git\":{\"createdTime\":1728311364000,\"updatedTime\":1728465755000,\"contributors\":[{\"name\":\"YAO\",\"email\":\"1964877312@qq.com\",\"commits\":1}]},\"readingTime\":{\"minutes\":0.69,\"words\":207},\"filePathRelative\":\"Yao_Pack/tutorial/vuepress-hope/10.图片预览插件.md\",\"localizedDate\":\"2024年10月7日\",\"excerpt\":\"\\n<div class=\\\"hint-container info\\\">\\n<p class=\\\"hint-container-title\\\">相关信息</p>\\n<p>觉得官方的图片预览插件点一下放大，点一下缩小太难用了，于是自己重新开发了一个图片预览插件。<br>\\n【可完美适配移动端】</p>\\n</div>\\n<blockquote>\\n<p>注意：得先在配置文件中禁用 vuepress 的图片预览。<br>\\n<code>plugins.photoSwipe: false</code></p>\\n</blockquote>\\n<p>该插件在 <code>VuePress</code> 中使用的方式如下:</p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
