import comp from "D:/node/Yaoweb5/.vscode/.vp-temp/pages/tutorial/vuepress-hope/klipse.html.vue"
const data = JSON.parse("{\"path\":\"/tutorial/vuepress-hope/klipse.html\",\"title\":\"6.Klipse 插件的使用\",\"lang\":\"zh-CN\",\"frontmatter\":{\"category\":[\"博客搭建教程\"],\"tag\":[\"教程\",\"工具\"],\"order\":6,\"permalink\":\"/tutorial/vuepress-hope/klipse.html\",\"description\":\"6.Klipse 插件的使用 相关信息 Klipse 是一个 JavaScript 插件，用于在技术博客中嵌入交互式代码片段。从技术层面上讲，Klipse 是一小段 JavaScript 代码，用于评估浏览器中的代码片段，并且可以在任何网页上插入。 Github 仓库地址: https://github.com/viebel/klipse 该插件在 V...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://yaoabcde.github.io/Yao/Yao/tutorial/vuepress-hope/klipse.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"YAO\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"6.Klipse 插件的使用\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"6.Klipse 插件的使用 相关信息 Klipse 是一个 JavaScript 插件，用于在技术博客中嵌入交互式代码片段。从技术层面上讲，Klipse 是一小段 JavaScript 代码，用于评估浏览器中的代码片段，并且可以在任何网页上插入。 Github 仓库地址: https://github.com/viebel/klipse 该插件在 V...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2024-10-09T09:22:35.000Z\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"教程\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"工具\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2024-10-09T09:22:35.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"6.Klipse 插件的使用\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":\\\"2024-10-09T09:22:35.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Yao\\\",\\\"url\\\":\\\"https://baidu.com\\\",\\\"email\\\":\\\"1964877312@qq.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"第一步： 编写 VuePress 插件\",\"slug\":\"第一步-编写-vuepress-插件\",\"link\":\"#第一步-编写-vuepress-插件\",\"children\":[]},{\"level\":2,\"title\":\"第二步：在 Markdown 中使用编写好的插件\",\"slug\":\"第二步-在-markdown-中使用编写好的插件\",\"link\":\"#第二步-在-markdown-中使用编写好的插件\",\"children\":[]},{\"level\":2,\"title\":\"最终效果如下\",\"slug\":\"最终效果如下\",\"link\":\"#最终效果如下\",\"children\":[]},{\"level\":2,\"title\":\"参考资料\",\"slug\":\"参考资料\",\"link\":\"#参考资料\",\"children\":[]}],\"git\":{\"createdTime\":1728311364000,\"updatedTime\":1728465755000,\"contributors\":[{\"name\":\"YAO\",\"email\":\"1964877312@qq.com\",\"commits\":1}]},\"readingTime\":{\"minutes\":1.18,\"words\":353},\"filePathRelative\":\"Yao_Pack/tutorial/vuepress-hope/6.Klipse插件的使用.md\",\"localizedDate\":\"2024年10月7日\",\"excerpt\":\"\\n<div class=\\\"hint-container info\\\">\\n<p class=\\\"hint-container-title\\\">相关信息</p>\\n<p>Klipse 是一个 JavaScript 插件，用于在技术博客中嵌入交互式代码片段。从技术层面上讲，Klipse 是一小段 JavaScript 代码，用于评估浏览器中的代码片段，并且可以在任何网页上插入。</p>\\n<p>Github 仓库地址: <a href=\\\"https://github.com/viebel/klipse\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">https://github.com/viebel/klipse</a></p>\\n</div>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
