import comp from "D:/node/Yaoweb5/.vscode/.vp-temp/pages/favorite/essays/elonmusk_saying.html.vue"
const data = JSON.parse("{\"path\":\"/favorite/essays/elonmusk_saying.html\",\"title\":\"伊隆·马斯克 (Elon Musk) 励志名言\",\"lang\":\"zh-CN\",\"frontmatter\":{\"permalink\":\"/favorite/essays/elonmusk_saying.html\",\"description\":\"伊隆·马斯克 (Elon Musk) 励志名言 相关信息 虽然不我确定这是不是 ElonMusk 的名言，但这些句子的确给了我很大的力量。 关于行动力 a-1 a-2 a-3 关于如何变得优秀 b-1 b-2 b-3 关于面对新事物 c-1 c-2 关于人生低谷 d-1 d-2 d-3 关于态度 e-1 e-2 e-3 最后 f-1f-1 愿每个人最后...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://blog.mo7.cc/Yao/favorite/essays/elonmusk_saying.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"YAO\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"伊隆·马斯克 (Elon Musk) 励志名言\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"伊隆·马斯克 (Elon Musk) 励志名言 相关信息 虽然不我确定这是不是 ElonMusk 的名言，但这些句子的确给了我很大的力量。 关于行动力 a-1 a-2 a-3 关于如何变得优秀 b-1 b-2 b-3 关于面对新事物 c-1 c-2 关于人生低谷 d-1 d-2 d-3 关于态度 e-1 e-2 e-3 最后 f-1f-1 愿每个人最后...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2024-10-07T16:48:13.000Z\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2024-10-07T16:48:13.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"伊隆·马斯克 (Elon Musk) 励志名言\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":\\\"2024-10-07T16:48:13.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Yao\\\",\\\"url\\\":\\\"https://baidu.com\\\",\\\"email\\\":\\\"1964877312@qq.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"关于行动力\",\"slug\":\"关于行动力\",\"link\":\"#关于行动力\",\"children\":[]},{\"level\":2,\"title\":\"关于如何变得优秀\",\"slug\":\"关于如何变得优秀\",\"link\":\"#关于如何变得优秀\",\"children\":[]},{\"level\":2,\"title\":\"关于面对新事物\",\"slug\":\"关于面对新事物\",\"link\":\"#关于面对新事物\",\"children\":[]},{\"level\":2,\"title\":\"关于人生低谷\",\"slug\":\"关于人生低谷\",\"link\":\"#关于人生低谷\",\"children\":[]},{\"level\":2,\"title\":\"关于态度\",\"slug\":\"关于态度\",\"link\":\"#关于态度\",\"children\":[]},{\"level\":2,\"title\":\"最后\",\"slug\":\"最后\",\"link\":\"#最后\",\"children\":[]}],\"git\":{\"createdTime\":1728311364000,\"updatedTime\":1728319693000,\"contributors\":[{\"name\":\"YAO\",\"email\":\"1964877312@qq.com\",\"commits\":3}]},\"readingTime\":{\"minutes\":0.48,\"words\":145},\"filePathRelative\":\"favorite/essays/伊隆·马斯克至理名言.md\",\"localizedDate\":\"2024年10月7日\",\"excerpt\":\"\\n<div class=\\\"hint-container info\\\">\\n<p class=\\\"hint-container-title\\\">相关信息</p>\\n<p>虽然不我确定这是不是 ElonMusk 的名言，但这些句子的确给了我很大的力量。</p>\\n</div>\\n<h2>关于行动力</h2>\\n<p><br>\\n<br>\\n</p>\\n<h2>关于如何变得优秀</h2>\\n<p><br>\\n<br>\\n</p>\\n<h2>关于面对新事物</h2>\\n<p><br>\\n</p>\\n<h2>关于人生低谷</h2>\\n<p><br>\\n<br>\\n</p>\\n<h2>关于态度</h2>\\n<p><br>\\n<br>\\n</p>\\n<h2>最后</h2>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
