import comp from "D:/node/Yaoweb5/.vscode/.vp-temp/pages/tutorial/ssh_jump.html.vue"
const data = JSON.parse("{\"path\":\"/tutorial/ssh_jump.html\",\"title\":\"4.ssh 跳板机\",\"lang\":\"zh-CN\",\"frontmatter\":{\"category\":[\"教程\"],\"tag\":[\"代理\",\"技巧\",\"教程\"],\"order\":3,\"permalink\":\"/tutorial/ssh_jump.html\",\"description\":\"4.ssh 跳板机 前面讲过 科学上网与本地代理，但是那只是在配置 http_proxy ，只适用于 http 请求。 http 请求并非网络的全部，有的时候可能还会用到 ssh 协议，比如 Github，但是 Github 的访问又不那么流畅，怎么办呢？ 什么是 SSH 什么是 SSH： https://info.support.huawei.com...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://yaoabcde.github.io/Yao/Yao/tutorial/ssh_jump.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"YAO\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"4.ssh 跳板机\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"4.ssh 跳板机 前面讲过 科学上网与本地代理，但是那只是在配置 http_proxy ，只适用于 http 请求。 http 请求并非网络的全部，有的时候可能还会用到 ssh 协议，比如 Github，但是 Github 的访问又不那么流畅，怎么办呢？ 什么是 SSH 什么是 SSH： https://info.support.huawei.com...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2024-10-09T09:22:35.000Z\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"代理\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"技巧\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"教程\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2024-10-09T09:22:35.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"4.ssh 跳板机\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":\\\"2024-10-09T09:22:35.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Yao\\\",\\\"url\\\":\\\"https://baidu.com\\\",\\\"email\\\":\\\"1964877312@qq.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"什么是 SSH\",\"slug\":\"什么是-ssh\",\"link\":\"#什么是-ssh\",\"children\":[]},{\"level\":2,\"title\":\"什么是 SSH跳板机\",\"slug\":\"什么是-ssh跳板机\",\"link\":\"#什么是-ssh跳板机\",\"children\":[]},{\"level\":2,\"title\":\"通过设置 ProxyCommand 把配置写到配置文件里面\",\"slug\":\"通过设置-proxycommand-把配置写到配置文件里面\",\"link\":\"#通过设置-proxycommand-把配置写到配置文件里面\",\"children\":[]}],\"git\":{\"createdTime\":1728311364000,\"updatedTime\":1728465755000,\"contributors\":[{\"name\":\"YAO\",\"email\":\"1964877312@qq.com\",\"commits\":1}]},\"readingTime\":{\"minutes\":1.29,\"words\":387},\"filePathRelative\":\"Yao_Pack/tutorial/4.ssh跳板机.md\",\"localizedDate\":\"2024年10月7日\",\"excerpt\":\"\\n<p>前面讲过 <a href=\\\"/tutorial/proxy_wall_ready.html\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">科学上网与本地代理</a>，但是那只是在配置 <code>http_proxy</code> ，只适用于 <code>http</code> 请求。</p>\\n<p><code>http</code> 请求并非网络的全部，有的时候可能还会用到 <code>ssh 协议</code>，比如 Github，但是 Github 的访问又不那么流畅，怎么办呢？</p>\\n<h2>什么是 <code>SSH</code></h2>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
