import comp from "D:/node/Yaoweb5/.vscode/.vp-temp/pages/tools/vscode/vscode_Draw.html.vue"
const data = JSON.parse("{\"path\":\"/tools/vscode/vscode_Draw.html\",\"title\":\"6.笔记的终极形态\",\"lang\":\"zh-CN\",\"frontmatter\":{\"category\":[\"工具\"],\"tag\":[\"VSCode\",\"目录\"],\"order\":6,\"permalink\":\"/tools/vscode/vscode_Draw.html\",\"description\":\"6.笔记的终极形态 个人笔记的终极形态 Markdown 编写， Github 存储， VSCode 插件， 本地画图无缝插入。 本文重点 一共三个 VSCode 插件 SVG 可以在本地编辑 SVG ，进行画图作业。 vscode-mindmap 开源的思维导图工具。作者基于源码 fork 进行优化，支持直接以 *.km.svg 的形式进行直接编辑和...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://yaoabcde.github.io/Yao/Yao/tools/vscode/vscode_Draw.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"YAO\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"6.笔记的终极形态\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"6.笔记的终极形态 个人笔记的终极形态 Markdown 编写， Github 存储， VSCode 插件， 本地画图无缝插入。 本文重点 一共三个 VSCode 插件 SVG 可以在本地编辑 SVG ，进行画图作业。 vscode-mindmap 开源的思维导图工具。作者基于源码 fork 进行优化，支持直接以 *.km.svg 的形式进行直接编辑和...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2024-10-07T16:48:13.000Z\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"VSCode\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"目录\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2024-10-07T16:48:13.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"6.笔记的终极形态\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":\\\"2024-10-07T16:48:13.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Yao\\\",\\\"url\\\":\\\"https://baidu.com\\\",\\\"email\\\":\\\"1964877312@qq.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"本文重点\",\"slug\":\"本文重点\",\"link\":\"#本文重点\",\"children\":[]},{\"level\":2,\"title\":\"起因\",\"slug\":\"起因\",\"link\":\"#起因\",\"children\":[]},{\"level\":2,\"title\":\"在线笔记\",\"slug\":\"在线笔记\",\"link\":\"#在线笔记\",\"children\":[]},{\"level\":2,\"title\":\"本地笔记\",\"slug\":\"本地笔记\",\"link\":\"#本地笔记\",\"children\":[]}],\"git\":{\"createdTime\":1728311364000,\"updatedTime\":1728319693000,\"contributors\":[{\"name\":\"YAO\",\"email\":\"1964877312@qq.com\",\"commits\":3}]},\"readingTime\":{\"minutes\":6.83,\"words\":2048},\"filePathRelative\":\"tools/vscode/6.笔记的终极形态.md\",\"localizedDate\":\"2024年10月7日\",\"excerpt\":\"\\n<div class=\\\"hint-container info\\\">\\n<p class=\\\"hint-container-title\\\">个人笔记的终极形态</p>\\n<p>Markdown 编写，<br>\\nGithub 存储，<br>\\nVSCode 插件，<br>\\n本地画图无缝插入。</p>\\n</div>\\n<h2>本文重点</h2>\\n<p>一共三个 VSCode 插件</p>\\n<blockquote>\\n<p><a href=\\\"https://marketplace.visualstudio.com/items?itemName=jock.svg\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">SVG</a><br>\\n可以在本地编辑 SVG ，进行画图作业。</p>\\n</blockquote>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
