import comp from "D:/node/Yaoweb5/.vscode/.vp-temp/pages/posts/book_list.html.vue"
const data = JSON.parse("{\"path\":\"/posts/book_list.html\",\"title\":\"墨七的书单\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"book\",\"order\":2,\"category\":[\"博文\"],\"tag\":[\"书单\"],\"permalink\":\"/posts/book_list.html\",\"description\":\"墨七的书单 《 行为科学统计 》 豆瓣读书-行为科学统计 这是本极佳的统计学入门书籍，不单讲理论，还会让你明白为什么要这么做，应该怎么做。 《 深入浅出数据分析 》 豆瓣读书-深入浅出数据分析 够浅白，然后还会讲一下为什么要这么做。唯一不好就是废话比较多吧，对有基础的人，不是很合适。 《 数据挖掘导论 》 豆瓣读书-数据挖掘导论 这个主要用于挖掘数据之...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://yaoabcde.github.io/Yao/Yao/posts/book_list.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"YAO\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"墨七的书单\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"墨七的书单 《 行为科学统计 》 豆瓣读书-行为科学统计 这是本极佳的统计学入门书籍，不单讲理论，还会让你明白为什么要这么做，应该怎么做。 《 深入浅出数据分析 》 豆瓣读书-深入浅出数据分析 够浅白，然后还会讲一下为什么要这么做。唯一不好就是废话比较多吧，对有基础的人，不是很合适。 《 数据挖掘导论 》 豆瓣读书-数据挖掘导论 这个主要用于挖掘数据之...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2024-10-09T09:22:35.000Z\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"书单\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2024-10-09T09:22:35.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"墨七的书单\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":\\\"2024-10-09T09:22:35.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Yao\\\",\\\"url\\\":\\\"https://baidu.com\\\",\\\"email\\\":\\\"1964877312@qq.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"《 行为科学统计 》\",\"slug\":\"《-行为科学统计-》\",\"link\":\"#《-行为科学统计-》\",\"children\":[]},{\"level\":2,\"title\":\"《 深入浅出数据分析 》\",\"slug\":\"《-深入浅出数据分析-》\",\"link\":\"#《-深入浅出数据分析-》\",\"children\":[]},{\"level\":2,\"title\":\"《 数据挖掘导论 》\",\"slug\":\"《-数据挖掘导论-》\",\"link\":\"#《-数据挖掘导论-》\",\"children\":[]},{\"level\":2,\"title\":\"《 金融市场与金融机构基础 》\",\"slug\":\"《-金融市场与金融机构基础-》\",\"link\":\"#《-金融市场与金融机构基础-》\",\"children\":[]},{\"level\":2,\"title\":\"《 投资学 》\",\"slug\":\"《-投资学-》\",\"link\":\"#《-投资学-》\",\"children\":[]},{\"level\":2,\"title\":\"Go 语言书单\",\"slug\":\"go-语言书单\",\"link\":\"#go-语言书单\",\"children\":[]}],\"git\":{\"createdTime\":1728311364000,\"updatedTime\":1728465755000,\"contributors\":[{\"name\":\"YAO\",\"email\":\"1964877312@qq.com\",\"commits\":1}]},\"readingTime\":{\"minutes\":1.35,\"words\":404},\"filePathRelative\":\"Yao_Pack/posts/2.墨七的书单.md\",\"localizedDate\":\"2024年10月7日\",\"excerpt\":\"\\n<h2>《 行为科学统计 》</h2>\\n<figure><figcaption></figcaption></figure>\\n<p><a href=\\\"https://book.douban.com/subject/36140702/\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">豆瓣读书-行为科学统计</a></p>\\n<blockquote>\\n<p>这是本极佳的统计学入门书籍，不单讲理论，还会让你明白为什么要这么做，应该怎么做。</p>\\n</blockquote>\\n<h2>《 深入浅出数据分析 》</h2>\\n<figure><figcaption></figcaption></figure>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
