import comp from "D:/node/Yaoweb5/.vscode/.vp-temp/pages/developer/front_end_web/fnm_ready.html.vue"
const data = JSON.parse("{\"path\":\"/developer/front_end_web/fnm_ready.html\",\"title\":\"2.fnm 管理 Nodejs\",\"lang\":\"zh-CN\",\"frontmatter\":{\"order\":2,\"category\":[\"前端\"],\"tag\":[\"工具\",\"技巧\",\"环境搭建\",\"教程\"],\"permalink\":\"/developer/front_end_web/fnm_ready.html\",\"description\":\"2.fnm 管理 Nodejs 当你本地存在多个项目，且依赖的 nodejs 版本不尽相同，就需要使用 nodejs 版本管理工具了，它允许同一台机器中多个 nodejs 版本共存且可以随时切换。 fnm 类似于 nvm，是一个 nodejs 版本管理工具， 他比 nvm 更加迅速，应该是目前已知最好的 nodejs 版本管理工具。 fnm 的特点是:...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://blog.mo7.cc/Yao/developer/front_end_web/fnm_ready.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"YAO\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"2.fnm 管理 Nodejs\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"2.fnm 管理 Nodejs 当你本地存在多个项目，且依赖的 nodejs 版本不尽相同，就需要使用 nodejs 版本管理工具了，它允许同一台机器中多个 nodejs 版本共存且可以随时切换。 fnm 类似于 nvm，是一个 nodejs 版本管理工具， 他比 nvm 更加迅速，应该是目前已知最好的 nodejs 版本管理工具。 fnm 的特点是:...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2024-10-07T16:48:13.000Z\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"工具\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"技巧\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"环境搭建\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"教程\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2024-10-07T16:48:13.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"2.fnm 管理 Nodejs\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":\\\"2024-10-07T16:48:13.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Yao\\\",\\\"url\\\":\\\"https://baidu.com\\\",\\\"email\\\":\\\"1964877312@qq.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"安装 fnm\",\"slug\":\"安装-fnm\",\"link\":\"#安装-fnm\",\"children\":[]},{\"level\":2,\"title\":\"fnm 的基本使用\",\"slug\":\"fnm-的基本使用\",\"link\":\"#fnm-的基本使用\",\"children\":[]},{\"level\":2,\"title\":\"Windows 环境下不推荐使用 fnm\",\"slug\":\"windows-环境下不推荐使用-fnm\",\"link\":\"#windows-环境下不推荐使用-fnm\",\"children\":[]}],\"git\":{\"createdTime\":1728311364000,\"updatedTime\":1728319693000,\"contributors\":[{\"name\":\"YAO\",\"email\":\"1964877312@qq.com\",\"commits\":3}]},\"readingTime\":{\"minutes\":1.59,\"words\":476},\"filePathRelative\":\"developer/front_end_web/2.fnm管理nodejs.md\",\"localizedDate\":\"2024年10月7日\",\"excerpt\":\"\\n<p>当你本地存在多个项目，且依赖的 nodejs 版本不尽相同，就需要使用 nodejs 版本管理工具了，它允许同一台机器中多个 nodejs 版本共存且可以随时切换。</p>\\n<p>fnm 类似于 nvm，是一个 nodejs 版本管理工具， 他比 nvm 更加迅速，应该是目前已知最好的 nodejs 版本管理工具。</p>\\n<p>fnm 的特点是:</p>\\n<ul>\\n<li>跨平台，支持 macOS、Windows、Linux。</li>\\n<li>使用 Rust 编写，速度快。发布为单文件，便于安装。</li>\\n<li>支持按应用自动切换 Node.js 版本。</li>\\n</ul>\\n\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
