import comp from "D:/node/Yaoweb5/.vscode/.vp-temp/pages/developer/front_end_web/npm.html.vue"
const data = JSON.parse("{\"path\":\"/developer/front_end_web/npm.html\",\"title\":\"npm 常用命令\",\"lang\":\"zh-CN\",\"frontmatter\":{\"category\":[\"前端\"],\"tag\":[\"工具\",\"技巧\"],\"permalink\":\"/developer/front_end_web/npm.html\",\"description\":\"npm 常用命令 注意 该文档有待补充和完善 阿里巴巴开源镜像站 https://developer.aliyun.com/mirror/ npm 镜像站 http://www.npmmirror.com/ Linux 设置本地代理 一些其它指令\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://yaoabcde.github.io/Yao/Yao/developer/front_end_web/npm.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"YAO\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"npm 常用命令\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"npm 常用命令 注意 该文档有待补充和完善 阿里巴巴开源镜像站 https://developer.aliyun.com/mirror/ npm 镜像站 http://www.npmmirror.com/ Linux 设置本地代理 一些其它指令\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2024-10-09T09:22:35.000Z\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"工具\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"技巧\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2024-10-09T09:22:35.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"npm 常用命令\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":\\\"2024-10-09T09:22:35.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Yao\\\",\\\"url\\\":\\\"https://baidu.com\\\",\\\"email\\\":\\\"1964877312@qq.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"阿里巴巴开源镜像站\",\"slug\":\"阿里巴巴开源镜像站\",\"link\":\"#阿里巴巴开源镜像站\",\"children\":[]},{\"level\":2,\"title\":\"npm 镜像站\",\"slug\":\"npm-镜像站\",\"link\":\"#npm-镜像站\",\"children\":[]},{\"level\":2,\"title\":\"Linux 设置本地代理\",\"slug\":\"linux-设置本地代理\",\"link\":\"#linux-设置本地代理\",\"children\":[]},{\"level\":2,\"title\":\"一些其它指令\",\"slug\":\"一些其它指令\",\"link\":\"#一些其它指令\",\"children\":[]}],\"git\":{\"createdTime\":1728311364000,\"updatedTime\":1728465755000,\"contributors\":[{\"name\":\"YAO\",\"email\":\"1964877312@qq.com\",\"commits\":1}]},\"readingTime\":{\"minutes\":0.35,\"words\":104},\"filePathRelative\":\"Yao_Pack/developer/front_end_web/npm常用指令.md\",\"localizedDate\":\"2024年10月7日\",\"excerpt\":\"\\n<div class=\\\"hint-container warning\\\">\\n<p class=\\\"hint-container-title\\\">注意</p>\\n<p>该文档有待补充和完善</p>\\n</div>\\n<h2>阿里巴巴开源镜像站</h2>\\n<p><a href=\\\"https://developer.aliyun.com/mirror/\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">https://developer.aliyun.com/mirror/</a></p>\\n<h2>npm 镜像站</h2>\\n<p><a href=\\\"http://www.npmmirror.com/\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">http://www.npmmirror.com/</a></p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
