import comp from "D:/node/Yaoweb5/.vscode/.vp-temp/pages/developer/golang/golang_viewpoint.html.vue"
const data = JSON.parse("{\"path\":\"/developer/golang/golang_viewpoint.html\",\"title\":\"当红开发语言 Go，真的是未来的技术主流吗？\",\"lang\":\"zh-CN\",\"frontmatter\":{\"order\":2,\"category\":[\"Golang\"],\"tag\":[\"工具\",\"教程\"],\"permalink\":\"/developer/golang/golang_viewpoint.html\",\"description\":\"当红开发语言 Go，真的是未来的技术主流吗？ 这个问题不能从技术角度考虑，要从【市场】角度考虑。 一、目前应用程序的主流是什么？ 桌面（Mac，Win，Linux） 移动 App（Android，Ios） Web（浏览器以各种 App、系统内套壳页面，鸿蒙，小程序 都算这一类吧~） 嵌入式（各种硬件交互，传感器，硬件控制，通信） 工控软件（嵌入式软件、...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://yaoabcde.github.io/Yao/Yao/developer/golang/golang_viewpoint.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"YAO\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"当红开发语言 Go，真的是未来的技术主流吗？\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"当红开发语言 Go，真的是未来的技术主流吗？ 这个问题不能从技术角度考虑，要从【市场】角度考虑。 一、目前应用程序的主流是什么？ 桌面（Mac，Win，Linux） 移动 App（Android，Ios） Web（浏览器以各种 App、系统内套壳页面，鸿蒙，小程序 都算这一类吧~） 嵌入式（各种硬件交互，传感器，硬件控制，通信） 工控软件（嵌入式软件、...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2024-10-07T16:48:13.000Z\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"工具\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"教程\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2024-10-07T16:48:13.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"当红开发语言 Go，真的是未来的技术主流吗？\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":\\\"2024-10-07T16:48:13.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Yao\\\",\\\"url\\\":\\\"https://baidu.com\\\",\\\"email\\\":\\\"1964877312@qq.com\\\"}]}\"]]},\"headers\":[],\"git\":{\"createdTime\":1728311364000,\"updatedTime\":1728319693000,\"contributors\":[{\"name\":\"YAO\",\"email\":\"1964877312@qq.com\",\"commits\":3}]},\"readingTime\":{\"minutes\":11.16,\"words\":3347},\"filePathRelative\":\"developer/golang/个人对于go语言的看法.md\",\"localizedDate\":\"2024年10月7日\",\"excerpt\":\"\\n<p>这个问题不能从技术角度考虑，要从【市场】角度考虑。</p>\\n<p>一、目前应用程序的主流是什么？</p>\\n<ol>\\n<li>桌面（Mac，Win，Linux）</li>\\n<li>移动 App（Android，Ios）</li>\\n<li>Web（浏览器以各种 App、系统内套壳页面，鸿蒙，小程序 都算这一类吧~）</li>\\n<li>嵌入式（各种硬件交互，传感器，硬件控制，通信）</li>\\n<li>工控软件（嵌入式软件、工业控制组态软件、PLC 编程软件等）</li>\\n<li>...等等等</li>\\n</ol>\\n<p>二、开展一个项目选用一个编程语言的标准是什么</p>\\n<ol>\\n<li>待开发系统的应用领域，即项目的应用范围。</li>\\n<li>应用形式（全平台，还是单平台，还是硬件集成，一体机）</li>\\n<li>应用规模（toB 还是 toC ，日活多少，顶峰访问量会有多少 ）</li>\\n<li>架构模式（分布式？事件总线？分层模式？有些语言在开发成熟的架构模式下，运维体系啥的）</li>\\n<li>支持平台（某些平台 SDK 只支持某一部分语言，甚至是指定语言）</li>\\n<li>开发周期（是可以慢工出细活，自研自控，还是说只图一个快，早上线早超生）</li>\\n<li>硬件要求（单片机还是服务器？是否要上集群和规模）</li>\\n<li>语言生态（生态丰富成熟的语言开发速度确实会比较快）</li>\\n<li>好不好招人（也就是所谓的用工成本）</li>\\n</ol>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
