import comp from "D:/node/Yaoweb5/.vscode/.vp-temp/pages/developer/golang/golang_install.html.vue"
const data = JSON.parse("{\"path\":\"/developer/golang/golang_install.html\",\"title\":\"1.安装\",\"lang\":\"zh-CN\",\"frontmatter\":{\"order\":1,\"category\":[\"Golang\"],\"tag\":[\"工具\",\"环境搭建\",\"教程\"],\"permalink\":\"/developer/golang/golang_install.html\",\"description\":\"1.安装 官网地址： https://golang.google.cn/ 国内 Wiki https://learnku.com/go/wikis Linux 可以无脑的依次执行以下命令: 注意！ 一定要区分系统的架构类型，尤其是常见的 amd 和 arm 架构。 每次版本更新时 只需要将版本号 go1.23.2 换成最新版本号即可。 此时 go 已经...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://yaoabcde.github.io/Yao/Yao/developer/golang/golang_install.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"YAO\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"1.安装\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"1.安装 官网地址： https://golang.google.cn/ 国内 Wiki https://learnku.com/go/wikis Linux 可以无脑的依次执行以下命令: 注意！ 一定要区分系统的架构类型，尤其是常见的 amd 和 arm 架构。 每次版本更新时 只需要将版本号 go1.23.2 换成最新版本号即可。 此时 go 已经...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"工具\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"环境搭建\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"教程\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"1.安装\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Yao\\\",\\\"url\\\":\\\"https://baidu.com\\\",\\\"email\\\":\\\"1964877312@qq.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Linux\",\"slug\":\"linux\",\"link\":\"#linux\",\"children\":[]},{\"level\":2,\"title\":\"Windows && MacOS\",\"slug\":\"windows-macos\",\"link\":\"#windows-macos\",\"children\":[]},{\"level\":2,\"title\":\"检查安装结果\",\"slug\":\"检查安装结果\",\"link\":\"#检查安装结果\",\"children\":[]},{\"level\":2,\"title\":\"设置代理\",\"slug\":\"设置代理\",\"link\":\"#设置代理\",\"children\":[]},{\"level\":2,\"title\":\"Hello World\",\"slug\":\"hello-world\",\"link\":\"#hello-world\",\"children\":[]},{\"level\":2,\"title\":\"多版本管理\",\"slug\":\"多版本管理\",\"link\":\"#多版本管理\",\"children\":[]}],\"git\":{\"createdTime\":null,\"updatedTime\":null,\"contributors\":[]},\"readingTime\":{\"minutes\":1.87,\"words\":561},\"filePathRelative\":\"Yao_Pack/developer/golang/1.安装.md\",\"excerpt\":\"\\n<p>官网地址：<br>\\n<a href=\\\"https://golang.google.cn/\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">https://golang.google.cn/</a></p>\\n<p>国内 Wiki<br>\\n<a href=\\\"https://learnku.com/go/wikis\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">https://learnku.com/go/wikis</a></p>\\n<h2>Linux</h2>\\n<p>可以无脑的依次执行以下命令:</p>\\n<div class=\\\"hint-container warning\\\">\\n<p class=\\\"hint-container-title\\\">注意！</p>\\n<p>一定要区分系统的架构类型，尤其是常见的 amd 和 arm 架构。<br>\\n每次版本更新时 只需要将版本号 <code>go1.23.2</code> 换成最新版本号即可。</p>\\n</div>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
